# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  # Aurora Corne Build
#  - board: nice_nano_v2
#    shield: splitkb_aurora_corne_left
#  - board: nice_nano_v2
#    shield: splitkb_aurora_corne_right
#  # Aurora Sweep Build
#  - board: nice_nano_v2
#    shield: splitkb_aurora_sweep_left
#  - board: nice_nano_v2
#    shield: splitkb_aurora_sweep_right
  # Aurora Sweep Build With Dongle
  # Before flashing your new firmware, you need to flash settings_reset firmware on all devices to ensure they can pair to each other.
  - board: nice_nano_v2
    shield: ferris_hub_dongle
  # Add these cmake-args to the peripherals you wish to use with the dongle
  - board: nice_nano_v2
    shield: ferris_hub
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # Reset Build
  - board: nice_nano_v2
    shield: settings_reset
